TARGET = 'syphonImpApp'
APP_SOURCES = ['syphonImpApp.cpp']
DEBUG = 0

env = Environment()
env = SConscript('../../scons/SConscript', exports = ['env'])

env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG'])
