Import('env')

from os.path import dirname

_INCLUDES = [Dir('../lib').abspath, Dir('../src').abspath]

_SOURCES = ['../src/syphonClient.mm', '../src/syphonServer.mm',
		'../src/syphonServerDirectory.mm', '../lib/SyphonNameboundClient.m']
_SOURCES = [Dir(dirname(s)).abspath + '/' + s for s in _SOURCES]

env.Append(CPPPATH = _INCLUDES)
env.Append(APP_SOURCES = _SOURCES)
env.Append(FRAMEWORKS = ['Syphon'])
env.Append(FRAMEWORKPATH = [Dir('../lib').abspath])

# copy Syphon.framework to app
if 'APP_TARGET' in env:
	fout = env['APP_TARGET'] + '.app/Contents/Frameworks/Syphon.framework'
	fin = Dir('../lib/Syphon.framework').abspath
	Command('#' + fout, fin, Copy(fout, fin))

Return('env')
